(window["webpackJsonp"] = window["webpackJsonp"] || []).push([["$slug"],{

/***/ "./src/routes/[slug].svelte":
/*!**********************************!*\
  !*** ./src/routes/[slug].svelte ***!
  \**********************************/
/*! exports provided: default, preload */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "preload", function() { return preload; });
/* harmony import */ var svelte_internal__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! svelte/internal */ "./node_modules/svelte/internal/index.mjs");
/* harmony import */ var _sanityClient_js__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! ./sanityClient.js */ "./src/routes/sanityClient.js");
/* harmony import */ var _components_CMSCard_svelte__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__(/*! ../components/CMSCard.svelte */ "./src/components/CMSCard.svelte");
/* src/routes/[slug].svelte generated by Svelte v3.23.2 */


const { console: console_1 } = svelte_internal__WEBPACK_IMPORTED_MODULE_0__["globals"];


const file = "src/routes/[slug].svelte";

function create_fragment(ctx) {
	let title_value;
	let t0;
	let section;
	let div1;
	let a0;
	let i;
	let t1;
	let t2;
	let article;
	let div0;
	let h2;
	let t3;
	let t4;
	let p0;
	let t5;
	let t6;
	let ul;
	let li0;
	let h30;
	let t7;
	let t8;
	let p1;
	let t9;
	let t10;
	let li1;
	let h31;
	let t11;
	let t12;
	let p2;
	let t13;
	let t14;
	let li2;
	let h32;
	let t15;
	let t16;
	let p3;
	let t17_value = (/*creditCardNeeded*/ ctx[2] ? "Yes" : "No") + "";
	let t17;
	let t18;
	let li3;
	let h33;
	let t19;
	let t20;
	let p4;
	let t21;
	let t22;
	let li4;
	let h34;
	let t23;
	let t24;
	let p5;
	let t25;
	let t26;
	let li5;
	let h35;
	let t27;
	let t28;
	let p6;
	let a1;
	let t29_value = Object(_components_CMSCard_svelte__WEBPACK_IMPORTED_MODULE_2__["getHostname"])(/*url*/ ctx[6]) + "";
	let t29;
	document.title = title_value = "About " + /*service*/ ctx[0].name + " | The Headless Project";

	const block = {
		c: function create() {
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			section = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("section");
			div1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			a0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("a");
			i = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("i");
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("\n      Back to list");
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			article = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("article");
			div0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			h2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("h2");
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(/*name*/ ctx[5]);
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			p0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("p");
			t5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(/*heading*/ ctx[4]);
			t6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			ul = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("ul");
			li0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("li");
			h30 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("h3");
			t7 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Elevator pitch");
			t8 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			p1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("p");
			t9 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(/*description*/ ctx[3]);
			t10 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			li1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("li");
			h31 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("h3");
			t11 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Billing cycle");
			t12 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			p2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("p");
			t13 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(/*billing*/ ctx[1]);
			t14 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			li2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("li");
			h32 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("h3");
			t15 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Credit card required");
			t16 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			p3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("p");
			t17 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(t17_value);
			t18 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			li3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("li");
			h33 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("h3");
			t19 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Pricing");
			t20 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			p4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("p");
			t21 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("TODO: Handle pricing");
			t22 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			li4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("li");
			h34 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("h3");
			t23 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Trusted by:");
			t24 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			p5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("p");
			t25 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("TODO: Map the `usedBy` logos/links");
			t26 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			li5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("li");
			h35 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("h3");
			t27 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Website:");
			t28 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			p6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("p");
			a1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("a");
			t29 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(t29_value);
			this.h();
		},
		l: function claim(nodes) {
			const head_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["query_selector_all"])("[data-svelte=\"svelte-a98j73\"]", document.head);
			head_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(nodes);
			section = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "SECTION", {});
			var section_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(section);
			div1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(section_nodes, "DIV", { class: true });
			var div1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div1);
			a0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div1_nodes, "A", { rel: true, class: true, href: true });
			var a0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(a0);
			i = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(a0_nodes, "I", { class: true, "aria-hidden": true });
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(i).forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(a0_nodes, "\n      Back to list");
			a0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div1_nodes);
			article = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div1_nodes, "ARTICLE", { class: true });
			var article_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(article);
			div0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(article_nodes, "DIV", { class: true });
			var div0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div0);
			h2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div0_nodes, "H2", { class: true });
			var h2_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(h2);
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(h2_nodes, /*name*/ ctx[5]);
			h2_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div0_nodes);
			p0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div0_nodes, "P", {});
			var p0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(p0);
			t5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p0_nodes, /*heading*/ ctx[4]);
			p0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(article_nodes);
			ul = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(article_nodes, "UL", {});
			var ul_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(ul);
			li0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(ul_nodes, "LI", { class: true });
			var li0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(li0);
			h30 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(li0_nodes, "H3", { class: true });
			var h30_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(h30);
			t7 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(h30_nodes, "Elevator pitch");
			h30_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t8 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(li0_nodes);
			p1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(li0_nodes, "P", { class: true });
			var p1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(p1);
			t9 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p1_nodes, /*description*/ ctx[3]);
			p1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			li0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t10 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(ul_nodes);
			li1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(ul_nodes, "LI", { class: true });
			var li1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(li1);
			h31 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(li1_nodes, "H3", { class: true });
			var h31_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(h31);
			t11 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(h31_nodes, "Billing cycle");
			h31_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t12 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(li1_nodes);
			p2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(li1_nodes, "P", { class: true });
			var p2_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(p2);
			t13 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p2_nodes, /*billing*/ ctx[1]);
			p2_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			li1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t14 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(ul_nodes);
			li2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(ul_nodes, "LI", { class: true });
			var li2_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(li2);
			h32 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(li2_nodes, "H3", { class: true });
			var h32_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(h32);
			t15 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(h32_nodes, "Credit card required");
			h32_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t16 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(li2_nodes);
			p3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(li2_nodes, "P", { class: true });
			var p3_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(p3);
			t17 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p3_nodes, t17_value);
			p3_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			li2_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t18 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(ul_nodes);
			li3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(ul_nodes, "LI", { class: true });
			var li3_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(li3);
			h33 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(li3_nodes, "H3", { class: true });
			var h33_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(h33);
			t19 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(h33_nodes, "Pricing");
			h33_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t20 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(li3_nodes);
			p4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(li3_nodes, "P", { class: true });
			var p4_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(p4);
			t21 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p4_nodes, "TODO: Handle pricing");
			p4_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			li3_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t22 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(ul_nodes);
			li4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(ul_nodes, "LI", { class: true });
			var li4_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(li4);
			h34 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(li4_nodes, "H3", { class: true });
			var h34_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(h34);
			t23 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(h34_nodes, "Trusted by:");
			h34_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t24 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(li4_nodes);
			p5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(li4_nodes, "P", { class: true });
			var p5_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(p5);
			t25 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p5_nodes, "TODO: Map the `usedBy` logos/links");
			p5_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			li4_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t26 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(ul_nodes);
			li5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(ul_nodes, "LI", { class: true });
			var li5_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(li5);
			h35 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(li5_nodes, "H3", { class: true });
			var h35_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(h35);
			t27 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(h35_nodes, "Website:");
			h35_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t28 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(li5_nodes);
			p6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(li5_nodes, "P", {});
			var p6_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(p6);

			a1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(p6_nodes, "A", {
				class: true,
				href: true,
				rel: true,
				target: true
			});

			var a1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(a1);
			t29 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(a1_nodes, t29_value);
			a1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			p6_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			li5_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			ul_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			article_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			section_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			this.h();
		},
		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(i, "class", "fa fa-angle-left");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(i, "aria-hidden", "true");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(i, file, 44, 6, 1223);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(a0, "rel", "prefetch");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(a0, "class", "block mb-4 text-sm text-gray-600");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(a0, "href", ".");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(a0, file, 43, 4, 1148);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(h2, "class", "text-xl text-primary");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(h2, file, 49, 8, 1425);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(p0, file, 50, 8, 1478);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div0, "class", "border-b border-solid border-gray-300 px-4 py-6");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div0, file, 48, 6, 1355);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(h30, "class", "lg:w-1/5 font-medium");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(h30, file, 58, 10, 1739);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(p1, "class", "text-gray-600");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(p1, file, 59, 10, 1802);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(li0, "class", "flex flex-col lg:flex-row p-4 bg-gray-100");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(li0, file, 57, 8, 1674);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(h31, "class", "lg:w-1/5 font-medium");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(h31, file, 62, 10, 1920);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(p2, "class", "text-gray-600");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(p2, file, 63, 10, 1982);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(li1, "class", "flex flex-col lg:flex-row p-4");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(li1, file, 61, 8, 1867);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(h32, "class", "lg:w-1/5 font-medium");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(h32, file, 66, 10, 2108);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(p3, "class", "text-gray-600");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(p3, file, 67, 10, 2177);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(li2, "class", "flex flex-col lg:flex-row p-4 bg-gray-100");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(li2, file, 65, 8, 2043);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(h33, "class", "lg:w-1/5 font-medium");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(h33, file, 70, 10, 2315);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(p4, "class", "italic text-gray-600");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(p4, file, 71, 10, 2371);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(li3, "class", "flex flex-col lg:flex-row p-4");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(li3, file, 69, 8, 2262);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(h34, "class", "lg:w-1/5 font-medium");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(h34, file, 86, 10, 2870);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(p5, "class", "italic text-gray-600");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(p5, file, 87, 10, 2930);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(li4, "class", "flex flex-col lg:flex-row p-4 bg-gray-100");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(li4, file, 85, 8, 2805);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(h35, "class", "lg:w-1/5 font-medium");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(h35, file, 93, 10, 3225);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(a1, "class", "text-primary");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(a1, "href", /*url*/ ctx[6]);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(a1, "rel", "noopener noreferrer nofollow");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(a1, "target", "_blank");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(a1, file, 95, 12, 3298);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(p6, file, 94, 10, 3282);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(li5, "class", "flex flex-col lg:flex-row p-4");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(li5, file, 92, 8, 3172);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(ul, file, 52, 6, 1514);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(article, "class", "shadow rounded bg-white");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(article, file, 47, 4, 1307);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div1, "class", "container mx-auto px-4 lg:px-0 py-12");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div1, file, 42, 2, 1093);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(section, file, 41, 0, 1081);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, t0, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, section, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(section, div1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div1, a0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(a0, i);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(a0, t1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div1, t2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div1, article);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(article, div0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div0, h2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(h2, t3);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div0, t4);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div0, p0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(p0, t5);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(article, t6);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(article, ul);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(ul, li0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(li0, h30);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(h30, t7);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(li0, t8);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(li0, p1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(p1, t9);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(ul, t10);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(ul, li1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(li1, h31);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(h31, t11);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(li1, t12);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(li1, p2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(p2, t13);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(ul, t14);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(ul, li2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(li2, h32);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(h32, t15);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(li2, t16);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(li2, p3);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(p3, t17);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(ul, t18);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(ul, li3);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(li3, h33);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(h33, t19);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(li3, t20);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(li3, p4);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(p4, t21);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(ul, t22);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(ul, li4);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(li4, h34);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(h34, t23);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(li4, t24);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(li4, p5);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(p5, t25);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(ul, t26);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(ul, li5);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(li5, h35);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(h35, t27);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(li5, t28);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(li5, p6);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(p6, a1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(a1, t29);
		},
		p: function update(ctx, [dirty]) {
			if (dirty & /*service*/ 1 && title_value !== (title_value = "About " + /*service*/ ctx[0].name + " | The Headless Project")) {
				document.title = title_value;
			}
		},
		i: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		o: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		d: function destroy(detaching) {
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(t0);
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(section);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_fragment.name,
		type: "component",
		source: "",
		ctx
	});

	return block;
}

async function preload({ params }) {
	const { slug } = params;
	const SERVICE_QUERY = `*[_type == "cms" && slug.current == $slug][0]{...}`;
	const FEATURES_QUERY = `*[_type == "cms" && features._ref in *[_type=="features"]._id ]{...}`;
	const service = await _sanityClient_js__WEBPACK_IMPORTED_MODULE_1__["default"].fetch(SERVICE_QUERY, { slug }).catch(err => this.error(500, err));
	return { service };
}

function instance($$self, $$props, $$invalidate) {
	let { service } = $$props;
	const { billing, creditCardNeeded, description, heading, name, url, usedBy } = service;
	console.log(service);
	const writable_props = ["service"];

	Object.keys($$props).forEach(key => {
		if (!~writable_props.indexOf(key) && key.slice(0, 2) !== "$$") console_1.warn(`<U5Bslugu5D> was created with unknown prop '${key}'`);
	});

	let { $$slots = {}, $$scope } = $$props;
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["validate_slots"])("U5Bslugu5D", $$slots, []);

	$$self.$set = $$props => {
		if ("service" in $$props) $$invalidate(0, service = $$props.service);
	};

	$$self.$capture_state = () => ({
		client: _sanityClient_js__WEBPACK_IMPORTED_MODULE_1__["default"],
		preload,
		getHostname: _components_CMSCard_svelte__WEBPACK_IMPORTED_MODULE_2__["getHostname"],
		service,
		billing,
		creditCardNeeded,
		description,
		heading,
		name,
		url,
		usedBy
	});

	$$self.$inject_state = $$props => {
		if ("service" in $$props) $$invalidate(0, service = $$props.service);
	};

	if ($$props && "$$inject" in $$props) {
		$$self.$inject_state($$props.$$inject);
	}

	return [service, billing, creditCardNeeded, description, heading, name, url];
}

class U5Bslugu5D extends svelte_internal__WEBPACK_IMPORTED_MODULE_0__["SvelteComponentDev"] {
	constructor(options) {
		super(options);
		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["init"])(this, options, instance, create_fragment, svelte_internal__WEBPACK_IMPORTED_MODULE_0__["safe_not_equal"], { service: 0 });

		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterComponent", {
			component: this,
			tagName: "U5Bslugu5D",
			options,
			id: create_fragment.name
		});

		const { ctx } = this.$$;
		const props = options.props || {};

		if (/*service*/ ctx[0] === undefined && !("service" in props)) {
			console_1.warn("<U5Bslugu5D> was created without expected prop 'service'");
		}
	}

	get service() {
		throw new Error("<U5Bslugu5D>: Props cannot be read directly from the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	set service(value) {
		throw new Error("<U5Bslugu5D>: Props cannot be set directly on the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}
}

/* harmony default export */ __webpack_exports__["default"] = (U5Bslugu5D);


/***/ })

}]);
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIndlYnBhY2s6Ly8vLi9zcmMvcm91dGVzL1tzbHVnXS5zdmVsdGUiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6Ijs7Ozs7Ozs7Ozs7Ozs7Ozs7OztBQUN5QztBQWFvQjs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozt1Q0FxRHpCLEdBQWdCLE1BQUcsS0FBSyxHQUFHLElBQUk7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O2lCQWtDcEQsOEVBQVcsU0FBQyxHQUFHOzt1REEvRGQsR0FBTyxJQUFDLElBQUk7Ozs7Ozs7Ozs7Ozs7OzhFQVdjLEdBQUk7OztpRkFDbEMsR0FBTzs7Ozs7Ozs7cUZBU2lCLEdBQVc7Ozs7Ozs7a0ZBSVgsR0FBTzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OEZBZEQsR0FBSTs7Ozs7aUdBQ2xDLEdBQU87Ozs7Ozs7Ozs7Ozs7OztxR0FTaUIsR0FBVzs7Ozs7Ozs7Ozs7OztrR0FJWCxHQUFPOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7d0ZBa0N0QixHQUFHOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7c0ZBM0RSLEdBQU8sSUFBQyxJQUFJOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztlQXBDSixPQUFPLEdBQUcsTUFBTTtTQUM1QixJQUFJLEtBQUssTUFBTTtPQUNqQixhQUFhO09BQ2IsY0FBYztPQUNkLE9BQU8sU0FBUyx3REFBTSxDQUN6QixLQUFLLENBQUMsYUFBYSxJQUFJLElBQUksSUFDM0IsS0FBSyxDQUFDLEdBQUcsSUFBSSxJQUFJLENBQUMsS0FBSyxDQUFDLEdBQUcsRUFBRSxHQUFHO1VBQzFCLE9BQU87Ozs7T0FNUCxPQUFPO1NBR2hCLE9BQU8sRUFDUCxnQkFBZ0IsRUFDaEIsV0FBVyxFQUNYLE9BQU8sRUFDUCxJQUFJLEVBQ0osR0FBRyxFQUNILE1BQU0sS0FDSixPQUFPO0NBRVgsT0FBTyxDQUFDLEdBQUcsQ0FBQyxPQUFPIiwiZmlsZSI6ImQ1ZDhiYzY1MGJhMzg4N2ExNTUyLyRzbHVnLiRzbHVnLmpzIiwic291cmNlc0NvbnRlbnQiOlsiPHNjcmlwdCBjb250ZXh0PVwibW9kdWxlXCI+XG4gIGltcG9ydCBjbGllbnQgZnJvbSBcIi4vc2FuaXR5Q2xpZW50LmpzXCI7XG4gIGV4cG9ydCBhc3luYyBmdW5jdGlvbiBwcmVsb2FkKHsgcGFyYW1zIH0pIHtcbiAgICBjb25zdCB7IHNsdWcgfSA9IHBhcmFtcztcbiAgICBjb25zdCBTRVJWSUNFX1FVRVJZID0gYCpbX3R5cGUgPT0gXCJjbXNcIiAmJiBzbHVnLmN1cnJlbnQgPT0gJHNsdWddWzBdey4uLn1gO1xuICAgIGNvbnN0IEZFQVRVUkVTX1FVRVJZID0gYCpbX3R5cGUgPT0gXCJjbXNcIiAmJiBmZWF0dXJlcy5fcmVmIGluICpbX3R5cGU9PVwiZmVhdHVyZXNcIl0uX2lkIF17Li4ufWA7XG4gICAgY29uc3Qgc2VydmljZSA9IGF3YWl0IGNsaWVudFxuICAgICAgLmZldGNoKFNFUlZJQ0VfUVVFUlksIHsgc2x1ZyB9KVxuICAgICAgLmNhdGNoKGVyciA9PiB0aGlzLmVycm9yKDUwMCwgZXJyKSk7XG4gICAgcmV0dXJuIHsgc2VydmljZSB9O1xuICB9XG48L3NjcmlwdD5cblxuPHNjcmlwdD5cbiAgaW1wb3J0IHsgZ2V0SG9zdG5hbWUgfSBmcm9tIFwiLi4vY29tcG9uZW50cy9DTVNDYXJkLnN2ZWx0ZVwiO1xuICBleHBvcnQgbGV0IHNlcnZpY2U7XG5cbiAgY29uc3Qge1xuICAgIGJpbGxpbmcsXG4gICAgY3JlZGl0Q2FyZE5lZWRlZCxcbiAgICBkZXNjcmlwdGlvbixcbiAgICBoZWFkaW5nLFxuICAgIG5hbWUsXG4gICAgdXJsLFxuICAgIHVzZWRCeVxuICB9ID0gc2VydmljZTtcblxuICBjb25zb2xlLmxvZyhzZXJ2aWNlKTtcbiAgLy8gZXhwb3J0IGxldCBpbmRleCA9IFwiLlwiO1xuICAvLyBleHBvcnQgbGV0IHByaWNlcyA9IEFycmF5LmZyb20oc2VydmljZS5wcmljaW5nKTtcbiAgLy8gY29uc29sZS5sb2cocHJpY2VzKTtcbiAgLy8gZXhwb3J0IGxldCBmZWF0dXJlcyA9IEFycmF5LmZyb20ocHJpY2VzKTtcbiAgLy8gY29uc29sZS5sb2coZmVhdHVyZXMpO1xuICAvLyBleHBvcnQgbGV0IHVzZWRCeXMgPSBBcnJheS5mcm9tKHNlcnZpY2UudXNlZEJ5KTtcbiAgLy8gY29uc29sZS5sb2codXNlZEJ5cyk7XG48L3NjcmlwdD5cblxuPHN2ZWx0ZTpoZWFkPlxuICA8dGl0bGU+QWJvdXQge3NlcnZpY2UubmFtZX0gfCBUaGUgSGVhZGxlc3MgUHJvamVjdDwvdGl0bGU+XG48L3N2ZWx0ZTpoZWFkPlxuXG48c2VjdGlvbj5cbiAgPGRpdiBjbGFzcz1cImNvbnRhaW5lciBteC1hdXRvIHB4LTQgbGc6cHgtMCBweS0xMlwiPlxuICAgIDxhIHJlbD1cInByZWZldGNoXCIgY2xhc3M9XCJibG9jayBtYi00IHRleHQtc20gdGV4dC1ncmF5LTYwMFwiIGhyZWY9XCIuXCI+XG4gICAgICA8aSBjbGFzcz1cImZhIGZhLWFuZ2xlLWxlZnRcIiBhcmlhLWhpZGRlbj1cInRydWVcIj48L2k+XG4gICAgICBCYWNrIHRvIGxpc3RcbiAgICA8L2E+XG4gICAgPGFydGljbGUgY2xhc3M9XCJzaGFkb3cgcm91bmRlZCBiZy13aGl0ZVwiPlxuICAgICAgPGRpdiBjbGFzcz1cImJvcmRlci1iIGJvcmRlci1zb2xpZCBib3JkZXItZ3JheS0zMDAgcHgtNCBweS02XCI+XG4gICAgICAgIDxoMiBjbGFzcz1cInRleHQteGwgdGV4dC1wcmltYXJ5XCI+e25hbWV9PC9oMj5cbiAgICAgICAgPHA+e2hlYWRpbmd9PC9wPlxuICAgICAgPC9kaXY+XG4gICAgICA8dWw+XG4gICAgICAgIDwhLS0gXG4gICAgICAgICAgSXQgbWlnaHQgYmUgYmVuZWZpY2lhbCB0byBmaW5kIGEgd2F5IHRvIG1hcCgpIHRoZXNlIGBsaWAgb3V0XG4gICAgICAgICAgc28gdGhhdCB0aGlzIG1hcmt1cCBpc24ndCBzbyByZWR1bmRhbnQuXG4gICAgICAgIC0tPlxuICAgICAgICA8bGkgY2xhc3M9XCJmbGV4IGZsZXgtY29sIGxnOmZsZXgtcm93IHAtNCBiZy1ncmF5LTEwMFwiPlxuICAgICAgICAgIDxoMyBjbGFzcz1cImxnOnctMS81IGZvbnQtbWVkaXVtXCI+RWxldmF0b3IgcGl0Y2g8L2gzPlxuICAgICAgICAgIDxwIGNsYXNzPVwidGV4dC1ncmF5LTYwMFwiPntkZXNjcmlwdGlvbn08L3A+XG4gICAgICAgIDwvbGk+XG4gICAgICAgIDxsaSBjbGFzcz1cImZsZXggZmxleC1jb2wgbGc6ZmxleC1yb3cgcC00XCI+XG4gICAgICAgICAgPGgzIGNsYXNzPVwibGc6dy0xLzUgZm9udC1tZWRpdW1cIj5CaWxsaW5nIGN5Y2xlPC9oMz5cbiAgICAgICAgICA8cCBjbGFzcz1cInRleHQtZ3JheS02MDBcIj57YmlsbGluZ308L3A+XG4gICAgICAgIDwvbGk+XG4gICAgICAgIDxsaSBjbGFzcz1cImZsZXggZmxleC1jb2wgbGc6ZmxleC1yb3cgcC00IGJnLWdyYXktMTAwXCI+XG4gICAgICAgICAgPGgzIGNsYXNzPVwibGc6dy0xLzUgZm9udC1tZWRpdW1cIj5DcmVkaXQgY2FyZCByZXF1aXJlZDwvaDM+XG4gICAgICAgICAgPHAgY2xhc3M9XCJ0ZXh0LWdyYXktNjAwXCI+e2NyZWRpdENhcmROZWVkZWQgPyAnWWVzJyA6ICdObyd9PC9wPlxuICAgICAgICA8L2xpPlxuICAgICAgICA8bGkgY2xhc3M9XCJmbGV4IGZsZXgtY29sIGxnOmZsZXgtcm93IHAtNFwiPlxuICAgICAgICAgIDxoMyBjbGFzcz1cImxnOnctMS81IGZvbnQtbWVkaXVtXCI+UHJpY2luZzwvaDM+XG4gICAgICAgICAgPHAgY2xhc3M9XCJpdGFsaWMgdGV4dC1ncmF5LTYwMFwiPlRPRE86IEhhbmRsZSBwcmljaW5nPC9wPlxuICAgICAgICAgIDwhLS0geyNlYWNoIHByaWNlcyBhcyBwcmljZX1cbiAgICAgICAgICAgIDxkaXY+XG4gICAgICAgICAgICAgIDxoMz57cHJpY2UudGllcn08L2gzPlxuICAgICAgICAgICAgICA8cD57cHJpY2UuZGVzY3JpcHRpb259PC9wPlxuICAgICAgICAgICAgICA8cD4ke3ByaWNlLnByaWNlfTwvcD5cbiAgICAgICAgICAgICAgPHVsPlxuICAgICAgICAgICAgICAgIHsjZWFjaCBmZWF0dXJlcyBhcyBmZWF0dXJlfVxuICAgICAgICAgICAgICAgICAgPGxpPntmZWF0dXJlfTwvbGk+XG4gICAgICAgICAgICAgICAgey9lYWNofVxuICAgICAgICAgICAgICA8L3VsPlxuICAgICAgICAgICAgPC9kaXY+XG4gICAgICAgICAgey9lYWNofSAtLT5cbiAgICAgICAgPC9saT5cbiAgICAgICAgPGxpIGNsYXNzPVwiZmxleCBmbGV4LWNvbCBsZzpmbGV4LXJvdyBwLTQgYmctZ3JheS0xMDBcIj5cbiAgICAgICAgICA8aDMgY2xhc3M9XCJsZzp3LTEvNSBmb250LW1lZGl1bVwiPlRydXN0ZWQgYnk6PC9oMz5cbiAgICAgICAgICA8cCBjbGFzcz1cIml0YWxpYyB0ZXh0LWdyYXktNjAwXCI+VE9ETzogTWFwIHRoZSBgdXNlZEJ5YCBsb2dvcy9saW5rczwvcD5cbiAgICAgICAgICA8IS0tIHsjZWFjaCB1c2VkQnlzIGFzIHVzZWRCeX1cbiAgICAgICAgICAgIDxhIHJlbD0nZXh0ZXJuYWwnIGhyZWY9e3VzZWRCeS51cmwgfHwgaW5kZXh9PjxkaXY+e3VzZWRCeS5uYW1lfTwvZGl2PjwvYT5cbiAgICAgICAgICB7L2VhY2h9IC0tPlxuICAgICAgICA8L2xpPlxuICAgICAgICA8bGkgY2xhc3M9XCJmbGV4IGZsZXgtY29sIGxnOmZsZXgtcm93IHAtNFwiPlxuICAgICAgICAgIDxoMyBjbGFzcz1cImxnOnctMS81IGZvbnQtbWVkaXVtXCI+V2Vic2l0ZTo8L2gzPlxuICAgICAgICAgIDxwPlxuICAgICAgICAgICAgPGFcbiAgICAgICAgICAgICAgY2xhc3M9XCJ0ZXh0LXByaW1hcnlcIlxuICAgICAgICAgICAgICBocmVmPVwie3VybH1cIlxuICAgICAgICAgICAgICByZWw9XCJub29wZW5lciBub3JlZmVycmVyIG5vZm9sbG93XCJcbiAgICAgICAgICAgICAgdGFyZ2V0PVwiX2JsYW5rXCJcbiAgICAgICAgICAgID5cbiAgICAgICAgICAgICAge2dldEhvc3RuYW1lKHVybCl9XG4gICAgICAgICAgICA8L2E+XG4gICAgICAgICAgPC9wPlxuICAgICAgICA8L2xpPlxuICAgICAgPC91bD5cbiAgICA8L2FydGljbGU+XG4gIDwvZGl2PlxuPC9zZWN0aW9uPlxuIl0sInNvdXJjZVJvb3QiOiIifQ==